using System.Collections.Generic;

// <auto-generated>
// 来源：Character.xlsx/c1
// 请勿手动修改；请在 Unity 中通过 Tools/Excel Table Converter 重新生成。
// </auto-generated>
public sealed class Character_c1
{
    public int id; // 唯一标识
    public string name; // 名称
    public int namekey; // 语言表的key
}

internal sealed class Character_c1Table
{
    private readonly Dictionary<int, Character_c1> rows = new Dictionary<int, Character_c1>()
    {
        [1] = new Character_c1
        {
            id = 1,
            name = "罗",
            namekey = 1,
        },
        [2] = new Character_c1
        {
            id = 2,
            name = "凯",
            namekey = 2,
        },
        [3] = new Character_c1
        {
            id = 3,
            name = "鸥",
            namekey = 3,
        },
    };

    public Character_c1 Get(int key)
    {
        Character_c1 row;
        if (!rows.TryGetValue(key, out row))
        {
            throw new KeyNotFoundException("表 Character_c1 中不存在 Key：" + key);
        }
        return row;
    }

    public bool TryGet(int key, out Character_c1 row)
    {
        return rows.TryGetValue(key, out row);
    }
}
