using System.Collections.Generic;

// <auto-generated>
// 来源：Character.xlsx/c2
// 请勿手动修改；请在 Unity 中通过 Tools/Excel Table Converter 重新生成。
// </auto-generated>
public sealed class Character_c2
{
    public int id; // 唯一标识
    public string name; // 名称
    public int namekey; // 语言表的key
}

internal sealed class Character_c2Table
{
    private readonly Dictionary<int, Character_c2> rows = new Dictionary<int, Character_c2>()
    {
        [1] = new Character_c2
        {
            id = 1,
            name = "罗",
            namekey = 1,
        },
        [2] = new Character_c2
        {
            id = 2,
            name = "凯",
            namekey = 2,
        },
        [3] = new Character_c2
        {
            id = 3,
            name = "鸥",
            namekey = 3,
        },
    };

    public Character_c2 Get(int key)
    {
        Character_c2 row;
        if (!rows.TryGetValue(key, out row))
        {
            throw new KeyNotFoundException("表 Character_c2 中不存在 Key：" + key);
        }
        return row;
    }

    public bool TryGet(int key, out Character_c2 row)
    {
        return rows.TryGetValue(key, out row);
    }
}
