// <auto-generated>
// 所有表数据必须通过 TableMgr 读取。请勿手动修改。
// </auto-generated>
public sealed class TableMgr
{
    public static readonly TableMgr Instance = new TableMgr();

    private readonly Character_c1Table character_c1Table = new Character_c1Table();
    private readonly Character_c2Table character_c2Table = new Character_c2Table();

    private TableMgr() { }

    public Character_c1 GetCharacter_c1(int key)
    {
        return character_c1Table.Get(key);
    }

    public bool TryGetCharacter_c1(int key, out Character_c1 row)
    {
        return character_c1Table.TryGet(key, out row);
    }

    public Character_c2 GetCharacter_c2(int key)
    {
        return character_c2Table.Get(key);
    }

    public bool TryGetCharacter_c2(int key, out Character_c2 row)
    {
        return character_c2Table.TryGet(key, out row);
    }
}
